apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esclient-storage
  labels:
    app: client
spec:
  storageClassName: "do-block-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esclient-config
data:
  elasticsearch.yml: |
    cluster.name: escluster_dev
    network.host: "0.0.0.0"
    node.master: "false"
    node.data: "false"
    node.ingest: "false"
    bootstrap.memory_lock: false
    cluster.initial_master_nodes: ["esmaster-0","esmaster-1","esmaster-2"]
    logger.org.elasticsearch.cluster.coordination.ClusterBootstrapService: TRACE
    logger.org.elasticsearch.discovery: TRACE
    discovery.zen.ping.unicast.hosts: elasticsearch-cluster
    discovery.zen.minimum_master_nodes: 3
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
  ES_JAVA_OPTS: -Xms256m -Xmx256m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esclient
  labels:
    role: client
spec:
  selector:
    matchLabels:
      role: client
  replicas: 2
  template:
    metadata:
      labels:
        role: client
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - client
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: esclient
        image: quay.io/coolpalani/docker-elasticsearch:7.1.0
        resources:
          limits:
            cpu: 0.5
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: esclient-storage
          mountPath: /data
        - name: elasticsearch-config
          mountPath: /elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
        - name: elasticsearch-config
          configMap:
            name: esclient-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
        - name: esclient-storage
          persistentVolumeClaim:
            claimName: esclient-storage